(function(root,factory,plug){factory(root,plug);})(window,function(root,plug){if(!root['$']||!root['jQuery']){throw new Error('This plug-in relies on jquery,Please introduce jQuery first ');}
var instance;var Dialog=function(options){return new Dialog.prototype.init(options);};
Dialog.prototype={constructor:Dialog,init:function(options){this.box=options.box||'body';this.dom=options.dom_sel_str||'';this.type=options.type||'tip';this.content=options.content||'content';this.effectIn=options.effectIn||'';this.effectOut=options.effectOut||'';this.hasMask=options.hasMask||true;this.time=options.time||1500;this.closeBtn=options.closeBtn||'';this.closeBtn1=options.closeBtn1||'';this.listener={};this.handler=[];this.show();},show:function(callback){if(instance)return;instance=this;var _this=this;if(this.type==='tip'){if(this.dom_sel_str){$(this.dom_sel_str).css({display:'block'}).addClass(this.effectIn);}else{createTip(this.box,this.content,this.effectIn);}
setTimeout(function(){_this.hide()},_this.time)}
if(this.type==='dialog'){$(this.box).css({'overflow':'hidden'});if(this.hasMask&&typeof this.hasMask==='boolean'){createMask(this.box);$('#dialog-mask').show();}else if(this.hasMask&&typeof this.hasMask==='string'){$(this.hasMask).show();}
if(this.dom_sel_str){$(this.dom_sel_str).css({position:'absolute',left:'50%',top:'50%',display:'block',zIndex:1000}).css({marginTop:$(this.dom_sel_str).height()/-2+'px',marginLeft:$(this.dom_sel_str).width()/-2+'px'}).addClass(this.effectIn);}else{console.error('你需要展示的dom结构呢？？');return;}
this.closeBtn&&$("body ."+this.closeBtn).one('click',function(){_this.hide(1);});
this.closeBtn1&&$("body ."+this.closeBtn1).one('click',function(){_this.hide(2);})}
return this;},hide:function(s){var _this=this;if(this.type==='tip'){if(_this.dom_sel_str){$(_this.dom_sel_str).removeClass(this.effectIn).addClass(this.effectOut);if(!this.effectOut){$(_this.dom_sel_str).css({display:'none'});instance=null;if(_this.handler.indexOf('remove')>-1){_this.emit('remove')}}else{$(_this.dom_sel_str).one('webkitAnimationEnd',function(){$(_this.dom_sel_str).css({display:'none'}).removeClass(this.effectOut).off('webkitAnimationEnd');instance=null;if(_this.handler.indexOf('remove')>-1){_this.emit('remove')}})}}else{$('#dialog-tips').removeClass(this.effectIn).addClass(this.effectOut);if(!this.effectOut){$('#dialog-tips').remove();instance=null;if(_this.handler.indexOf('remove')>-1){_this.emit('remove')}}else{$('#dialog-tips').one('webkitAnimationEnd',function(){$(this).remove();instance=null;if(_this.handler.indexOf('remove')>-1){_this.emit('remove')}})}}}
if(this.type==='dialog'){if(this.hasMask&&typeof this.hasMask==='boolean'){var t=$('#dialog-mask');}else if(this.hasMask&&typeof this.hasMask==='string'){var t=$(this.hasMask);}
if(this.effectOut){$(this.dom_sel_str).removeClass(_this.effectIn).addClass(this.effectOut);$(this.dom_sel_str).one('webkitAnimationEnd',function(){$(_this.dom_sel_str).css({display:'none'}).removeClass(_this.effectOut).off('webkitAnimationEnd');t.css({display:'none'});$('#dialog-mask').remove();$(_this.box).css({'overflow':'auto'});instance=null;_this.closeBtn&&$("body ."+_this.closeBtn).off('click');_this.closeBtn1&&$("body ."+_this.closeBtn1).off('click');if(_this.closeBtn1){if(s==2&&_this.handler.indexOf('remove')>-1){_this.emit('remove');return;}
if(s==1&&_this.handler.indexOf('close')>-1){_this.emit('close');}}else{if(_this.handler.indexOf('remove')>-1){_this.emit('remove');}}})}else{$(_this.dom_sel_str).css({display:'none'}).removeClass(_this.effectIn);t.css({display:'none'});$('#dialog-mask').remove();instance=null;_this.closeBtn&&$("body ."+_this.closeBtn).off('click');_this.closeBtn1&&$("body ."+_this.closeBtn1).off('click');$(this.box).css({'overflow':'auto'});if(_this.closeBtn1){if(s==2&&_this.handler.indexOf('remove')>-1){_this.emit('remove');return;}
if(s==1&&_this.handler.indexOf('close')>-1){_this.emit('close');return;}}else{if(_this.handler.indexOf('remove')>-1){_this.emit('remove');}}}}
return this;},on:function(type,fn){this.handler.push(type);if(typeof this.listener[type]==='undefined'){this.listener[type]=[];}
if(typeof fn==='function'){this.listener[type].push(fn);}
return this;},emit:function(type){var fnArr=this.listener[type];for(var i=0;i<fnArr.length;i++){if(typeof fnArr[i]==='function'){fnArr[i]({type:type})}}
return this;},off:function(type,fn){var fnArr=this.listener[type];if(typeof fn==='function'||fn){for(var i=0;i<fnArr;i++){if(fnArr[i]===fn){this._listeners[type].splice(i,1);break;}}}else{delete this.listener[type];}
return this;}};
Dialog.prototype.init.prototype=Dialog.prototype;function createTip(dom,content,effect){$(dom).append('<div id="dialog-tips" style="display:inline-block;padding:5px 12px;background:rgba(0,0,0,.8);color:#fff;position:absolute;top:50%;left:50%;border-radius:5px;z-index:1000">'+content+'</div>');$('#dialog-tips').css({marginLeft:$('#dialog-tips').width()/-2+'px',marginTop:$('#dialog-tips').height()/-2+'px'}).addClass(effect);}
function createMask(box){$(box).append('<div id="dialog-mask" style="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.8);z-index:99;"></div>')}
root[plug]=Dialog;},'Dialog');